import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import Navbar from './components/Navbar.jsx';
import './globals.css';

import Footer from './components/Footer.jsx';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Metadata can optionally be defined in JS as well:
export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                 
          <Navbar />
      

        {/* 👇 Main content with top padding to avoid being hidden */}
        <main className="pt-28">
          {children}
        </main>
    <Footer/>

        </body>
      </html>
    </ClerkProvider>
  );
}
